Added newline to the standard out footer message
rikatz/kubepug pull request #452
Opened 2023-09-15 16:14 UTC by arahja

This PR is in reference to #451 
Added newline to the standard out footer message so that the prompt shows up on a new line after the program runs.

2023-09-17 09:14 UTC, cpanato requested changes

2023-09-17 09:14 UTC, cpanato commented on pkg/formatter/stdout.go
> +	footer = "Kubepug validates the APIs using Kubernetes markers. To know what are the deprecated and deleted APIS it checks, please go to https://kubepug.xyz/status/ \n"
thanks!

please change in the line 91 instead

```
s = fmt.Sprintf("%s\n\n%s\n", s, footer)
```

2023-09-18 18:06 UTC, arahja commented
Updated PR with the change @cpanato requested. Please let me know if there is anything else I can/should do.

2023-09-18 18:10 UTC, cpanato approved these changes
Thank you

2023-09-18 18:12 UTC, merged